### ISSUE TITLE
If the heading of the csv contain " quote it fails. 

### ISSUE THREAD

**Issue by kevbook** [knrz/CSV.js#27]
Maybe the heading has to be escaped.

**Comment by knrz** [comment]
Could you provide an example CSV?

**Comment by kevbook** [comment]
FYI. I am using the module on the browser. 
I have attached 2 files. Sample 1 will run fine. Sample 2 will error out since it has quotes on the heading.

http://cl.ly/0k0N1z0v2Q3d/sample.csv - sample 1
http://cl.ly/3O1X26362L2Z/sample2.csv - sample 2
