### ISSUE TITLE
AMD (requirejs) not working

### ISSUE THREAD

**Issue by matejkramny** [knrz/CSV.js#29]
1. I defined the path for require in the config.
2. `require(['csv'], function (csv) { /* csv = undefined */ })`
3. Added csv to the shim object, made it export 'CSV' as it is in the source code..
4. Require still not recognising csv for some reason

Its really strange, has CSV.js been tried with require.js?

Thanks!

**Comment by knrz** [comment]
To be honest I've never tried Require.js, so I just copied the output format that I think underscore.js uses. Let me look into this.

**Comment by matejkramny** [comment]
Ok thank you!

**Comment by knrz** [comment]
Could you by any chance throw me a skeleton RequireJS project with CSV loaded up? I'm lost :smile:

**Comment by matejkramny** [comment]
Ok will do.. I have been meaning to set up an empty skeleton project anyway.

(i'll let you know, should be done by end of day UK time)

**Comment by matejkramny** [comment]
Here you go as promised :).

https://github.com/matejkramny/angular-requirejs-starter

**Comment by knrz** [comment]
Thanks for the starter :+1: :smiley: :shipit:

**Comment by muzuiget** [comment]
Thanks god this bug fix 19 days ago.

@knrz When you release a version to bower?

**Comment by knrz** [comment]
@muzuiget 2 weeks ago. Version 3.6.3 has the fix.

**Comment by muzuiget** [comment]
@knrz But https://github.com/knrz/CSV.js/releases doesn't has the version tag, so bower can't install by `#3.6.3`

**Comment by knrz** [comment]
Oh whoops.

**Comment by muzuiget** [comment]
:+1:
