### ISSUE TITLE
Sporadic failures when null involved

### ISSUE THREAD

**Issue by elmart** [knrz/CSV.js#30]
I find this little lib very useful, but I've stumbled upon a strange failure, happening sometimes (not always) when null values are involved.
A sample reproduction on Chrome DevTools console:
```javascript
> a=data[12]
["2015-07-15 00:00:00.000", 711, "ihstelekom", null, null]
> b=data[13]
[null, null, "sifcepsa", 724, "2015-07-16 12:00:00.000"]
> new CSV([a]).encode()
""2015-07-15 00:00:00.000",711,"ihstelekom",,"
> new CSV([b]).encode()
",,"sifcepsa",724,"2015-07-16 12:00:00.000""
> new CSV([a,b]).encode()
""2015-07-15 00:00:00.000",711,"ihstelekom",,<new-line>"null",,"sifcepsa",,"
```
As it can be seen, encoding a or b separately works ok. But encoding both of them fails (there's a spurious "null" value in b's encoded value, instead of the expected "nothing".
I did take a quick glance but didn't find the culprit. Could you help, please?

**Comment by knrz** [comment]
The way the parser/encoder works is it uses the first line/object/array as the template for further data. From `a` it expects the first data type to be a string, so it encodes the first item of `b` as a string.

**Comment by elmart** [comment]
Ok, I see. But, null is a proper value for a string variable, different from the string "null". IMO, null values should always be encoded as "", no matter their type. 
Would you agree to that?

**Comment by knrz** [comment]
Using the first row as a template, any column with a `null` will always cast that column as a null. If that column is `"null"` (string with word null) then that column will be cast as a string.

One of the aspects of this library is that it doesn't check the types of each object, but rather only the types of the first object.

In your example, from `a`, the first column is deemed to be a `string` type. As such, the first item in each subsequence array has `String(object)` called on it.

**Comment by elmart** [comment]
I understand you've taken the design decision not to check individual values' types.
But a design decision should not affect result correctness.
And in this case, results are not correct.
So, it's not a feature, it's a bug.
If, as a result of such decision, your lib can't handle datasets where first row contains nulls, you should:
- Fix it. There are easy ways, such as adding a config option with an array of types, or a sample row.
- Or , as a minimum, clearly state that in the intro docs ("This lib can't handle arbitrary data, but only data where first row has no null values.").
I could have easily issued a PR to solve this, but seeing you attitude, I think I won't.
Cheers.

**Comment by knrz** [comment]
@elmart you're right. I mishandled this through zeal.

However, CSV.js does provide the ability to [configure it with an array of types](https://github.com/knrz/CSV.js#casting).

Example for your dataset:

```javascript
CSV.encode([a, b], { cast: ["String", "Primitive", "String", "Primitive", "String"] })
/*
 * "2015-07-15 00:00:00.000",711,"ihstelekom",,"null"
 * "null",,"sifcepsa",724,"2015-07-16 12:00:00.000"
 */
```

**Comment by elmart** [comment]
Ok, thanks for reconsidering. Your words make me see I was wrong about you, too. Sorry for that.
I hand't realized the possibility you mention, about provinding an array of types.
Unfortunately, that doesn't match my needs, as I'd like to have null strings serialized as "" instead of "null".
Closing this for now. Will reopen if I come to a solution satisfactory for both.
Thanks.
