### ISSUE TITLE
Option to not ignore empty lines

### ISSUE THREAD

**Issue by muzuiget** [knrz/CSV.js#33]
I don't know why this [commit](https://github.com/knrz/CSV.js/commit/87b960367105b4a7db9921d6eeaa78df7eaebc03) is a bug should be fix, so v3.6.4 is a breaking change and break my code, and let me busy this morning :cry: 

If ignore empty lines, we can’t one-to-one align the row index between parsing code and csv editor. For example, I generate a csv let use to edit, and use a empty line separate each section for for pretty look.

```csv
"title"
"desc"
"command"
"" <- as a separator
"User ID"
"integer"
"uid"
"1234"
```

When parse back the csv, if ignore the empty lines, I need to shift the row index, it is hard to debug because the `rows` which return by `parse()`, the array index is different from csv editor.

So, I request a option the let me setting this behavior.

**Comment by knrz** [comment]
Because this isn't part of the spec for [CSV](https://tools.ietf.org/html/rfc4180). The line separator *is* `\r\n` or `\r` or `\n`.

**Comment by muzuiget** [comment]
It is not `\r\n\r\n`, is `\r\n""\r\n`, which have an double quote between them.

And Python standard library csv module will keep these lines as well.
